export const apps_all = {
  pro: [
    { app: 0, code: "PROJECT", name: "案件管理" },
    { app: 0, code: "PROJECT_DETAIL_1", name: "案件詳細_板東" },
    { app: 0, code: "CUSTOMER", name: "顧客マスタ" },
    { app: 0, code: "ACTIVITY_HISTORY", name: "活動履歴" },
    { app: 0, code: "NEXT_ACTION", name: "次のアクション" },
    { app: 0, code: "PROJECT_DETAIL_2", name: "案件詳細_八尾" },
    { app: 0, code: "PROJECT_DETAIL_3", name: "案件詳細_官庁" },
    { app: 0, code: "ORDER_SLIP", name: "売上登録" },
    { app: 0, code: "ORDER_HISTORY", name: "売上履歴" },
    { app: 0, code: "SALES_SUMMARY", name: "営業集計" },
    { app: 0, code: "DELIVERY_PLAN_BULK", name: "配送予定一括登録" },
    { app: 0, code: "DELIVERY_PLAN_INDIVIDUAL", name: "担当者別配送予定" },
    { app: 0, code: "KPI_PEOPLE_CENTRIC", name: "KPI一括登録(人中心)" },
    { app: 0, code: "KPI_WORK_CENTRIC", name: "KPI一括登録(作業中心)" },
    { app: 0, code: "KPI_PERSONAL_TASK", name: "KPI個人別作業タスク" },
    { app: 0, code: "EVENT_LOG", name: "イベント履歴" },
    { app: 0, code: "STOCK_LIST", name: "在庫管理" },
    { app: 0, code: "EXPENSES", name: "経費" },
    { app: 0, code: "NOTIFICATION", name: "問屋・メーカーからのお知らせ" },
    { app: 0, code: "KGI", name: "KGIアプリ" },
    { app: 0, code: "SALES_TARGET", name: "売上目標" }
  ],
  dev: [
    { app: 126, code: "PROJECT", name: "【開発】案件管理" },
    { app: 127, code: "PROJECT_DETAIL_1", name: "【開発】案件詳細_板東" },
    { app: 125, code: "CUSTOMER", name: "【開発】顧客マスタ" },
    { app: 129, code: "ACTIVITY_HISTORY", name: "【開発】活動履歴" },
    { app: 131, code: "NEXT_ACTION", name: "【開発】次のアクション" },
    { app: 130, code: "PROJECT_DETAIL_2", name: "【開発】案件詳細_八尾" },
    { app: 128, code: "PROJECT_DETAIL_3", name: "【開発】案件詳細_官庁" },
    { app: 136, code: "ORDER_SLIP", name: "【開発】売上登録" },
    { app: 135, code: "ORDER_HISTORY", name: "【開発】売上履歴" },
    { app: 137, code: "SALES_SUMMARY", name: "【開発】営業集計" },
    { app: 132, code: "DELIVERY_PLAN_BULK", name: "【開発】配送予定一括登録" },
    { app: 124, code: "DELIVERY_PLAN_INDIVIDUAL", name: "【開発】担当者別配送予定" },
    { app: 143, code: "KPI_PEOPLE_CENTRIC", name: "【開発】KPI一括登録(人中心)" },
    { app: 145, code: "KPI_WORK_CENTRIC", name: "【開発】KPI一括登録(作業中心)" },
    { app: 141, code: "KPI_PERSONAL_TASK", name: "【開発】KPI個人別作業タスク" },
    { app: 149, code: "EVENT_LOG", name: "【開発】イベント履歴" },
    { app: 150, code: "STOCK_LIST", name: "【開発】在庫管理" },
    { app: 151, code: "EXPENSES", name: "【開発】経費" },
    { app: 152, code: "NOTIFICATION", name: "【開発】問屋・メーカーからのお知らせ" },
    { app: 154, code: "KGI", name: "【開発】KGIアプリ" },
    { app: 153, code: "SALES_TARGET", name: "【開発】売上目標" }
  ]
};
